[package]
name = "crosses-core"
version = "0.1.0"
edition = "2021"

[features]
default = [ "std", "serde" ]
std = []

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

